forge "http://forge.puppetlabs.com"

# Bootstrap provisioning
#mod 'vagrantbootstrap', :path => '/vagrant/puppet/local_modules/vagrantbootstrap'

mod 'stahnma/epel'

# Module from git
# mod 'puppetlabs/apache',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apache.git'

# Module from the forge
# mod 'puppetlabs/vcsrepo'

# Local modules?
# mod 'mymodule', :path => './local_modules/mymodule'
# mod 'mysecondmodule', :path => './local_modules/mysecondmodule'
